adminapp/urls.py
from django.conf.urls import url
from django.urls import path
from django.views.generic import TemplateView

from adminapp.views import common_views, login_views, staff_views, company_views, project_views, building_views, \
    flat_views, buildingplan_views, flatplan_views, component_views, reset_password, datatables, profile_views, \
    projectplan_views, task_views, notification_views, update_database, misc_views
from django.conf import settings
from django.views.static import serve
urlpatterns = [
    url(r'^$', common_views.IndexView.as_view(), name='index'),
    url(r'^login/$', login_views.LoginView.as_view(), name='login'),
    url(r'^logout/$', login_views.LogoutView.as_view(), name='logout'),
    url(r'^forget-password/$', reset_password.ResetPasswordRequestView.as_view(), name='forget-password'),
    url(r'^reset-password/$', reset_password.ResetPasswordView.as_view(), name='reset-password'),

    url(r'^profile/update/$', profile_views.ProfileUpdateView.as_view(), name='profile-update'),
    url(r'^change-password/$', profile_views.ChangePassword.as_view(), name='change-password'),

    url(r'^staffs/$', staff_views.StaffsView.as_view(), name='staffs'),
    url(r'^staffs/add/$', staff_views.StaffFormView.as_view(), name='staffs-add'),
    url(r'^staffs/update/(?P<pk>[\w-]+)/$', staff_views.StaffUpdateView.as_view(), name='staffs-update'),
    url(r'^staffs/delete/$', staff_views.StaffsView.delete, name='staffs-delete'),
    url(r'^staff-list/$', datatables.StaffListView.as_view(), name='staffList'),
    url(r'^staffs/change-password/(?P<pk>[\w-]+)$', staff_views.StaffPasswordChangeView.as_view(),name='staffs-password-update'),

    url(r'^companies/$', company_views.CompaniesView.as_view(), name='companies'),
    url(r'^companies/add/$', company_views.CompanyFormView.as_view(), name='companies-add'),
    url(r'^companies/update/(?P<pk>[\w-]+)/$', company_views.CompanyUpdateView.as_view(), name='companies-update'),
    url(r'^companies/delete/$', company_views.CompaniesView.delete, name='companies-delete'),
    url(r'^company-list/$', datatables.CompanyListView.as_view(), name='companyList'),
    url(r'^companies/change-password/(?P<pk>[\w-]+)$', company_views.CompanyPasswordChangeView.as_view(),name='companies-password-update'),

    url(r'^change-user-status/$', staff_views.StaffsView.change_user_status, name='change-user-status'),

    url(r'^projects/$', project_views.ProjectsView.as_view(), name='projects'),
    url(r'^projects/add/$', project_views.ProjectFormView.as_view(), name='projects-add'),
    url(r'^projects/update/(?P<pk>[\w-]+)/$', project_views.ProjectUpdateView.as_view(), name='projects-update'),
    url(r'^projects/delete/$', project_views.ProjectsView.delete, name='projects-delete'),
    url(r'^project-list/$', datatables.ProjectListView.as_view(), name='projectList'),

    url(r'^change-project-status/$', project_views.ProjectsView.change_project_status, name='change-project-status'),

    url(r'^projects/(?P<project_id>[\w-]+)/buildings/$', building_views.BuildingsView.as_view(), name='buildings'),
    url(r'^building-list/$', datatables.BuildingListView.as_view(), name='buildingList'),
    url(r'^projects/(?P<project_id>[\w-]+)/buildings/add/$', building_views.BuildingFormView.as_view(), name='buildings-add'),
    url(r'^buildings/update/(?P<pk>[\w-]+)/$', building_views.BuildingUpdateView.as_view(), name='buildings-update'),
    url(r'^buildings/delete/$', building_views.BuildingsView.delete, name='buildings-delete'),
    url(r'^buildings/qr/(?P<pk>[\w-]+)/$', building_views.BuildingsView.preview_qr, name='buildings-qr'),
    url(r'^buildings/(?P<building_id>[\w-]+)/tasks/$', task_views.TasksView.get_all_building_tasks, name='building-tasks'),

    url(r'^buildings/(?P<building_id>[\w-]+)/flats/$', flat_views.FlatsView.as_view(), name='flats'),
    url(r'^flats-list/$', datatables.FlatListView.as_view(), name='flatList'),
    url(r'^buildings/(?P<building_id>[\w-]+)/flats/add/$', flat_views.FlatFormView.as_view(), name='flats-add'),
    url(r'^flats/update/(?P<pk>[\w-]+)/$', flat_views.FlatUpdateView.as_view(), name='flats-update'),
    url(r'^flats/delete/$', flat_views.FlatsView.delete, name='flats-delete'),
    url(r'^flats/qr/(?P<pk>[\w-]+)/$', flat_views.FlatsView.preview_qr, name='flats-qr'),
    url(r'^flats/(?P<flat_id>[\w-]+)/tasks/$', task_views.TasksView.get_all_flat_tasks, name='flat-tasks'),

    url(r'^components/$', component_views.ComponentView.as_view(), name='components'),
    url(r'^components/add/$', component_views.ComponentAddView.as_view(), name='component-add'),
    url(r'^components/update/(?P<pk>[\w-]+)/$', component_views.ComponentUpdateView.as_view(), name='component-update'),
    url(r'^components/delete/$', component_views.ComponentView.delete, name='component-delete'),

    url(r'^building-plans/$', buildingplan_views.BuildingPlansView.get_all_plans_by_active_building, name='building-plans'),
    url(r'^building/(?P<building_id>[\w-]+)/plan/add/$', buildingplan_views.BuildingPlansAddView.as_view(), name='building-plan-add'),
    # url(r'^building-plan/update/(?P<pk>[\w-]+)/$', buildingplan_views.BuildingPlansUpdateView.as_view(), name='building-plan-update'),
    url(r'^building-plan/delete/$', buildingplan_views.BuildingPlansView.delete, name='building-plan-delete'),

    url(r'^flat-plans/$', flatplan_views.FlatPlansView.get_all_plans_by_active_flat, name='flat-plans'),
    url(r'^flat/(?P<flat_id>[\w-]+)/plan/add/$', flatplan_views.FlatPlansAddView.as_view(), name='flat-plan-add'),
    # url(r'^flat-plan/update/(?P<pk>[\w-]+)/$', flatplan_views.FlatPlansUpdateView.as_view(), name='flat-plan-update'),
    url(r'^flat-plan/delete/$', flatplan_views.FlatPlansView.delete, name='flat-plan-delete'),

    url(r'^project-plans/$', projectplan_views.ProjectPlansView.get_all_plans_by_active_project, name='project-plans'),
    url(r'^project/(?P<project_id>[\w-]+)/plan/add/$', projectplan_views.ProjectPlansAddView.as_view(), name='project-plan-add'),
    # url(r'^project-plan/update/(?P<pk>[\w-]+)/$', projectplan_views.ProjectPlansUpdateView.as_view(), name='project-plan-update'),
    url(r'^project-plan/delete/$', projectplan_views.ProjectPlansView.delete, name='project-plan-delete'),

    url(r'^sw.js', (TemplateView.as_view(template_name="sw.js", content_type='application/javascript', )), name='sw.js'),

    url(r'^qr-to-png/(?P<qr_id>[\w-]+)/$', common_views.QRResponse.as_view(), name='qr-to-png'),

    url(r'^current-buildings/$', common_views.CurrentProjects.get_all_current_buildings, name='current-buildings'),
    url(r'^current-project-buildings/$', common_views.CurrentProjects.get_all_buildings_by_active_project, name='current-project-buildings'),
    url(r'^current-project-flats/$', common_views.CurrentProjects.get_all_flats_by_active_building, name='current-project-flats'),
    url(r'^current-flats/$', common_views.CurrentProjects.get_all_current_flats, name='current-flats'),

    url(r'^get-pending-components/$', task_views.TasksView.get_pending_components, name='get-pending-components'),
    url(r'^get-done-components/$', task_views.TasksView.get_done_components, name='get-done-components'),
    url(r'^get-all-components/$', task_views.TasksView.get_all_components, name='get-all-components'),
    url(r'^get-component-tasks/$', task_views.TasksView.get_component_tasks, name='get-component-tasks'),
    url(r'^get-handworker-list/$', task_views.TasksView.get_handwerker_list, name='get-handworker-list'),
    url(r'^assign-handworker/$', task_views.TasksView.assign_handwerker, name='assign-handworker'),
    # url(r'^get-active-tasks/$', task_views.TasksView.get_active_tasks, name='get-active-tasks'),

    url(r'^tasks/(?P<task_id>[\w-]+)/$', task_views.TaskDetailsView.as_view(), name='task-details'),
    url(r'^save-task-description/$', task_views.TaskDetailsView.save_task_description, name='save-task-description'),
    url(r'^change-task-status/$', task_views.TaskDetailsView.change_task_status, name='change-task-status'),
    url(r'^change-task-deadline/$', task_views.TaskDetailsView.change_task_deadline, name='change-task-deadline'),
    url(r'^add-new-comment/(?P<task_id>[\w-]+)/$', task_views.TaskDetailsView.add_new_comment, name='add-new-comment'),
    url(r'^get-more-comments/$', task_views.TaskDetailsView.get_more_comments, name='get-more-comments'),
    url(r'^add-task-followers/$', task_views.TaskDetailsView.add_task_followers, name='add-task-followers'),
    url(r'^get-new-notifications/$', notification_views.NotificationsView.get_new_notifications, name='get-new-notifications'),
    url(r'^get-all-notifications/$', notification_views.NotificationsView.as_view(), name='get-all-notifications'),
    url(r'^get-more-notifications/$', notification_views.NotificationsView.get_more_notifications, name='get-more-notifications'),
    url(r'^read-all-notifications/$', notification_views.NotificationsView.read_all_notification, name='read-all-notifications'),
    url(r'^privacy_policy/$', misc_views.privacy_policy.as_view(), name='privacy_policy'),

    url(r'^update-database/$', update_database.UpdateDatabaseView.as_view(), name='update-database'),
    url(r'^update-database-request/$', update_database.UpdateDatabaseView.update_database, name='update-database-request'),


]

supplementer/urls.py
import notifications.urls
from django.conf.urls import include, url
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('', include('adminapp.urls')),
    path('api/', include('serviceapp.urls')),
    url('^inbox/notifications/', include(notifications.urls, namespace='notifications')),
]

from django.conf.urls.static import static
from django.conf import settings

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

adminapp/forms/building_form.py
from django import forms
from adminapp.models import Buildings
import re


class BuildingForm(forms.ModelForm):
    hause_number = forms.CharField(required=True, max_length=45)
    display_number = forms.CharField(required=True, max_length=45)
    grundung = forms.CharField(required=False, max_length=45)
    aussenwande_eg_og_dg = forms.CharField(required=False, max_length=45)
    fenster_beschattung = forms.CharField(required=False, max_length=45)
    dach = forms.CharField(required=False, max_length=45)
    description = forms.CharField(required=False, max_length=1000)

    class Meta:
        model = Buildings
        fields = ('hause_number', 'display_number', 'description', 'grundung', 'aussenwande_eg_og_dg', 'fenster_beschattung', 'dach')

    def clean(self):
        cleaned_data = super(BuildingForm, self).clean()

    def save(self, request, commit=True):
        cleaned_data = super(BuildingForm, self).clean()
        obj = super(BuildingForm, self).save(commit=False)
        obj.project_id = request.project_id
        obj.created_by = request.user
        obj.updated_by = request.user
        obj.save()
        return obj

    def update(self, request, commit=True):
        cleaned_data = super(BuildingForm, self).clean()
        obj = super(BuildingForm, self).save(commit=False)
        obj.updated_by = request.user
        obj.save()
        return obj

    def process(self):
        cd = self.cleaned_data

adminapp/forms/buildingplans_form.py
from django import forms
from adminapp.models import BuildingPlans


class BuildingPlansForm(forms.ModelForm):
    title = forms.CharField(label="title", max_length=100)
    plan_file = forms.FileField(label="plan_file", required=False)
    file_type = forms.CharField(max_length=45, required=False)

    class Meta:
        model = BuildingPlans
        fields = ('title', 'plan_file', 'file_type')

    def clean(self):
        cleaned_data = super(BuildingPlansForm, self).clean()
        title = cleaned_data.get('title')
        if BuildingPlans.objects.filter(title=title).exclude(pk=self.instance.id).exists():
            self.add_error('title', 'Plan is already exists.')

    def save(self, request, commit=True):
        cleaned_data = super(BuildingPlansForm, self).clean()
        obj = super(BuildingPlansForm, self).save(commit=False)
        obj.created_by = request.user
        obj.file_type = cleaned_data.get('plan_file').name.split('.')[-1]
        obj.building_id = request.building_id
        obj.save()
        return obj

    # def update(self, request, commit=True):
    #     cleaned_data = super(BuildingPlansForm, self).clean()
    #     obj = super(BuildingPlansForm, self).save(commit=False)
    #     obj.created_by = request.user
    #     obj.file_type = cleaned_data.get('plan_file').name.split('.')[-1]
    #     obj.building_id = 3
    #     obj.save()
    #     return obj

    def process(self):
        cd = self.cleaned_data

adminapp/forms/component_form.py
from django import forms
from adminapp.models import Components
import re


class ComponentForm(forms.ModelForm):
    name = forms.CharField(label='name', min_length=3, max_length=100)
    static_description = forms.CharField(label='description', required=False, max_length=1000)
    parent_id = forms.IntegerField(label='parent', required=False)
    type = forms.CharField(label='type', required=False, max_length=255)
    building = forms.BooleanField(label='building', required=False)
    flat = forms.BooleanField(label='flat', required=False)

    class Meta:
        model = Components
        db_table = "components"
        fields = ('name', 'static_description', 'parent_id', 'type', 'building', 'flat')

    def clean(self):
        cleaned_data = super(ComponentForm, self).clean()
        # name = cleaned_data.get('name')
        # if Components.objects.filter(name=name).exclude(pk=self.instance.id).exists():
        #     self.add_error('name', 'Component is already exists.')

    def clean_type(self):
        data = self.cleaned_data['type']
        # do some stuff
        if data == '':
            data = None
        return data

    def save(self, request, commit=True):
        cleaned_data = super(ComponentForm, self).clean()
        obj = super(ComponentForm, self).save(commit=False)
        obj.created_by = request.user
        obj.updated_by = request.user
        obj.parent_id = cleaned_data.get('parent_id')
        obj.save()
        return obj

    def update(self, request, commit=True):
        cleaned_data = super(ComponentForm, self).clean()
        obj = super(ComponentForm, self).save(commit=False)
        obj.created_by = request.user
        obj.updated_by = request.user
        obj.save()
        return obj

    def process(self):
        cd = self.cleaned_data

adminapp/forms/project_form.py
from django import forms
from adminapp.models import Projects
import re


class ProjectForm(forms.ModelForm):
    name = forms.CharField(required=True, max_length=200)
    address = forms.CharField(required=False, max_length=1000)
    description = forms.CharField(required=False, max_length=1000)
    type = forms.CharField(required=False, max_length=100)
    city = forms.CharField(required=False, max_length=100)
    energetic_standard = forms.CharField(required=False, max_length=100)
    start_date = forms.DateTimeField(required=False)
    end_date = forms.DateTimeField(required=False)

    class Meta:
        model = Projects
        fields = ('name', 'address', 'description', 'type', 'city', 'energetic_standard', 'start_date', 'end_date')

    def clean(self):
        cleaned_data = super(ProjectForm, self).clean()
        name = cleaned_data.get('name')
        if Projects.objects.filter(name=name).exclude(pk=self.instance.id).exists():
            self.add_error('name', 'Project name is already exists.')

    def save(self, request, commit=True):
        cleaned_data = super(ProjectForm, self).clean()
        obj = super(ProjectForm, self).save(commit=False)
        obj.created_by = request.user
        obj.updated_by = request.user
        obj.save()
        return obj

    def update(self, request, commit=True):
        cleaned_data = super(ProjectForm, self).clean()
        obj = super(ProjectForm, self).save(commit=False)
        obj.updated_by = request.user
        obj.save()
        return obj

    def process(self):
        cd = self.cleaned_data

adminapp/views.py
from django.shortcuts import render

# Create your views here.

adminapp/views/login_views.py
from django.shortcuts import render, redirect
from django.views import generic
from django.contrib.auth import authenticate, login, logout


class LoginView(generic.DetailView):
    def get(self, request):
        if request.user.is_authenticated:
            return redirect('index')
        else:
            return render(request, 'profiles/login.html')

    def post(self,request):
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None and user.is_staff:
            login(request, user)
            user_data = {
                "id": user.id
            }
            request.session['is_logged_in'] = True
            request.session['supplementer_user'] = user_data
            request.session.modified = True
            return redirect('index')
        else:
            # Return an 'invalid login' error message.
            return render(request, 'profiles/login.html', {'msg': 'Authenntication failed.Wrong Username or Password. Try Again'})


class LogoutView(generic.DetailView):
    def get(self, request):
        if 'active_project' in request.session:
            del request.session['active_project']
        if 'active_building' in request.session:
            del request.session['active_building']
        if 'active_flat' in request.session:
            del request.session['active_flat']
        logout(request)
        return redirect('login')

adminapp/templates/projects/add_plans.html
{% extends "layout/main.html" %}
{% block content %}
    {% load staticfiles %}
        <div class="content-header">
                <div class="container-fluid">
                    <div class="row mb-2">
                        <!-- /.col -->
                        <div class="col-sm-6">
                            <!-- <ol class="breadcrumb float-sm-left">
                                <li class="breadcrumb-item"><a href="#">Home</a></li>
                                <li class="breadcrumb-item active">Add Plan</li>
                            </ol> -->
                        </div>
                        <!-- /.col -->
                    </div>
                    <!-- /.row -->
                </div>
                <!-- /.container-fluid -->
            </div>
            <!-- /.content-header -->

            <!-- Main content -->
            <div class="content">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="card">
                                <div class="card-header">

                                    <div class="row">
                                        <div class="col-sm">
                                            <h3 class="card-title">Pläne Hinzufügen</h3>
                                        </div>
                                    </div>
                                </div>
                                <!-- /.card-header -->
                                <div class="card-body">
                                    <form action="{% url 'project-plan-add' project_id=project_id %}" method="post" enctype="multipart/form-data" id="form-add-project-plans">
                                        {% csrf_token %}
                                        {{ form.non_field_errors }}
                                        <div class="row">
                                            <div class="col-sm-3  col-xs-12 align-items-center justify-content-center chg_image_profile">
                                                <div class="row">
                                                    <div class="col-sm-8 offset-sm-2 col-xs-12">
                                                        <div class="form-group">
                                                            <div class=" imgUp">
                                                                <div class="imagePreview"></div>
                                                                <label class="btn btn-primary btn_up_image w-100">
                                                                    Plän auswählen<input type="file" class="uploadFile img" value="Select plan" name="plan_file" style="width: 0px;height: 0px;overflow: hidden;" required="">
                                                                </label>
                                                                {{ form.plan_file.errors }}
                                                            </div><!-- col-2 -->
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="col-sm-8 col-xs-12">
                                                <div class="form-group">
                                                    <label for="{{ form.title.id_for_label }}">Plan name<span class="required-cls">*</span></label>
                                                    <input type="text" class="form-control" id="id_title" name="title" placeholder="Enter Plan name" data-parsley-trigger="change" required="">
                                                    {{ form.title.errors }}
                                                </div>
                                                <button type="submit" class="btn btn-primary">Add Plan</button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                                    <!-- /.card-body -->
                            </div>
                                <!-- /.col-lg-6 -->
                        </div>
                            <!-- /.row -->
                    </div>
                        <!-- /.container-fluid -->
                </div>
                    <!-- /.content -->
            </div>
    <script type="text/javascript">
        $('.uploadFile').change(function () {
            var file = $('.uploadFile')[0].files[0].name.split('.');
            file = file[file.length - 1];

            if (file != 'pdf') {
                $('.imagePreview').attr('background-image', 'url(../../static/assets/images/file.png)');
            }
            $(this).prev('label').text(file);
        });
        $(function () {
            $("#form-add-project-plans").validate({
                ignore: '.ignore',
                focusInvalid: true,
                rules: {
                    'title': {
                        required: true
                    },
                    'plan_file': {
                        required: true
                    }
                }
            });
            $('#form-add-project-plans').on('submit', function () {
                if ($(this).valid()) {
                    return true;
                }
                return false;
            });
        });
    </script>
{% endblock %}

adminapp/templates/projects/add_project.html
{% extends "layout/main.html" %}
{% block content %}
    {% load staticfiles %}
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-left">
                        <li class="breadcrumb-item"><a href="{% url 'index' %}">Home</a></li>
                        <li class="breadcrumb-item active">Add Project</li>
                    </ol>
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-header">

                            <div class="row">
                                <div class="col-sm">
                                    <h3 class="card-title">Add Project</h3>
                                </div>
                            </div>
                        </div>
                        <!-- /.card-header -->
                        <div class="card-body">
                            <form id="form-add-project" action="{% url 'projects-add' %}" method="post">
                                {% csrf_token %}
                                {{ form.non_field_errors }}
                                <div class="row">
                                    <div class="col-sm-6 col-xs-12">
                                        <div class="form-group">
                                            <label for="{{ form.name.id_for_label }}">Name<span class="required-cls">*</span></label>
                                            <input type="text" id="id_name" name="name"
                                                       class="form-control" placeholder="Enter name">
                                                {{ form.name.errors }}
                                        </div>
                                        <div class="form-group">
                                            <label for="{{ form.type.id_for_label }}">Type</label>
                                            <input type="text" id="id_type" name="type"
                                                       class="form-control" placeholder="Enter type">
                                                {{ form.type.errors }}
                                        </div>
                                    </div>
                                    <div class="col-sm-6 col-xs-12">
                                        <div class="form-group">
                                            <label for="{{ form.city.id_for_label }}">City</label>
                                            <input type="text" id="id_city" name="city"
                                                       class="form-control" placeholder="Enter city">
                                                {{ form.city.errors }}
                                        </div>
                                        <div class="form-group">
                                            <label for="{{ form.energetic_standard.id_for_label }}">Energetic Standard</label>
                                            <input type="text" id="id_energetic_standard" name="energetic_standard"
                                                       class="form-control" placeholder="Enter Energetic Standard">
                                                {{ form.energetic_standard.errors }}
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-sm-4 col-xs-12">
                                        <div class="form-group">
                                            <label for="{{ form.start_date.id_for_label }}">Start Date</label>
                                            <input  width="100%" placeholder="yyyy-mm-dd" id="id_start_date" class="form-control datepicker-start-date date-picker" name="start_date">
                                                {{ form.start_date.errors }}
                                        </div>
                                    </div>
                                    <div class="col-sm-4 col-xs-12">
                                        <div class="form-group">
                                            <label for="{{ form.end_date.id_for_label }}">End Date</label>
                                            <input  width="100%" placeholder="yyyy-mm-dd" id="id_end_date" class="form-control datepicker-end-date date-picker" name="end_date">
                                                {{ form.end_date.errors }}
                                        </div>
                                    </div>
                                    <div class="col-sm-12 col-xs-12">

                                        <div class="form-group">
                                            <label for="{{ form.address.id_for_label }}">Address</label>
                                            <textarea class="form-control" rows="3" id="id_address" name="address" placeholder="Enter address"></textarea>
                                                {{ form.address.errors }}
                                        </div>

                                    </div>
                                    <div class="col-sm-12 col-xs-12">
                                        <div class="form-group">
                                            <label for="{{ form.description.id_for_label }}">Description</label>
                                            <textarea class="form-control" rows="3" id="id_description" name="description" placeholder="Enter Description"></textarea>
                                                {{ form.description.errors }}
                                        </div>
                                    </div>
                                    <div class="col-sm-6 col-xs-12">
                                        <button type="submit" class="btn btn-primary">Add Project</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.col-lg-6 -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /.container-fluid -->
    </div>
    <!-- /.content -->
    <script>
        $(function () {
            $("#form-add-project").validate({
                ignore: '.ignore',
                focusInvalid: true,
                rules: {
                    'name': {
                        required: true
                    },
                    'address': {
                        required: false
                    },
                    'description': {
                        required: false
                    },
                    'type': {
                        required: false
                    },
                    'city': {
                        required: false
                    },
                    'energetic_standard': {
                        required: false,
                    },
                    'start_date': {
                        required: false
                    },
                    'end_date': {
                        required: false
                    }
                }
            });
            $('#form-add-project').on('submit', function () {
                if ($(this).valid()) {
                    return true;
                }
                return false;
            });
        });
    </script>

{% endblock %}