adminapp/urls.py
from django.conf.urls import url
from django.urls import path
from django.views.generic import TemplateView

from adminapp.views import common_views, login_views, staff_views, company_views, project_views, building_views, \
    flat_views, buildingplan_views, flatplan_views, component_views, reset_password, datatables, profile_views, \
    projectplan_views, task_views, notification_views, update_database, misc_views
from django.conf import settings
from django.views.static import serve
urlpatterns = [
    url(r'^$', common_views.IndexView.as_view(), name='index'),
    url(r'^login/$', login_views.LoginView.as_view(), name='login'),
    url(r'^logout/$', login_views.LogoutView.as_view(), name='logout'),
    url(r'^forget-password/$', reset_password.ResetPasswordRequestView.as_view(), name='forget-password'),
    url(r'^reset-password/$', reset_password.ResetPasswordView.as_view(), name='reset-password'),

    url(r'^profile/update/$', profile_views.ProfileUpdateView.as_view(), name='profile-update'),
    url(r'^change-password/$', profile_views.ChangePassword.as_view(), name='change-password'),

    url(r'^staffs/$', staff_views.StaffsView.as_view(), name='staffs'),
    url(r'^staffs/add/$', staff_views.StaffFormView.as_view(), name='staffs-add'),
    url(r'^staffs/update/(?P<pk>[\w-]+)/$', staff_views.StaffUpdateView.as_view(), name='staffs-update'),
    url(r'^staffs/delete/$', staff_views.StaffsView.delete, name='staffs-delete'),
    url(r'^staff-list/$', datatables.StaffListView.as_view(), name='staffList'),
    url(r'^staffs/change-password/(?P<pk>[\w-]+)$', staff_views.StaffPasswordChangeView.as_view(),name='staffs-password-update'),

    url(r'^companies/$', company_views.CompaniesView.as_view(), name='companies'),
    url(r'^companies/add/$', company_views.CompanyFormView.as_view(), name='companies-add'),
    url(r'^companies/update/(?P<pk>[\w-]+)/$', company_views.CompanyUpdateView.as_view(), name='companies-update'),
    url(r'^companies/delete/$', company_views.CompaniesView.delete, name='companies-delete'),
    url(r'^company-list/$', datatables.CompanyListView.as_view(), name='companyList'),
    url(r'^companies/change-password/(?P<pk>[\w-]+)$', company_views.CompanyPasswordChangeView.as_view(),name='companies-password-update'),

    url(r'^change-user-status/$', staff_views.StaffsView.change_user_status, name='change-user-status'),

    url(r'^projects/$', project_views.ProjectsView.as_view(), name='projects'),
    url(r'^projects/add/$', project_views.ProjectFormView.as_view(), name='projects-add'),
    url(r'^projects/update/(?P<pk>[\w-]+)/$', project_views.ProjectUpdateView.as_view(), name='projects-update'),
    url(r'^projects/delete/$', project_views.ProjectsView.delete, name='projects-delete'),
    url(r'^project-list/$', datatables.ProjectListView.as_view(), name='projectList'),

    url(r'^change-project-status/$', project_views.ProjectsView.change_project_status, name='change-project-status'),

    url(r'^projects/(?P<project_id>[\w-]+)/buildings/$', building_views.BuildingsView.as_view(), name='buildings'),
    url(r'^building-list/$', datatables.BuildingListView.as_view(), name='buildingList'),
    url(r'^projects/(?P<project_id>[\w-]+)/buildings/add/$', building_views.BuildingFormView.as_view(), name='buildings-add'),
    url(r'^buildings/update/(?P<pk>[\w-]+)/$', building_views.BuildingUpdateView.as_view(), name='buildings-update'),
    url(r'^buildings/delete/$', building_views.BuildingsView.delete, name='buildings-delete'),
    url(r'^buildings/qr/(?P<pk>[\w-]+)/$', building_views.BuildingsView.preview_qr, name='buildings-qr'),
    url(r'^buildings/(?P<building_id>[\w-]+)/tasks/$', task_views.TasksView.get_all_building_tasks, name='building-tasks'),

    url(r'^buildings/(?P<building_id>[\w-]+)/flats/$', flat_views.FlatsView.as_view(), name='flats'),
    url(r'^flats-list/$', datatables.FlatListView.as_view(), name='flatList'),
    url(r'^buildings/(?P<building_id>[\w-]+)/flats/add/$', flat_views.FlatFormView.as_view(), name='flats-add'),
    url(r'^flats/update/(?P<pk>[\w-]+)/$', flat_views.FlatUpdateView.as_view(), name='flats-update'),
    url(r'^flats/delete/$', flat_views.FlatsView.delete, name='flats-delete'),
    url(r'^flats/qr/(?P<pk>[\w-]+)/$', flat_views.FlatsView.preview_qr, name='flats-qr'),
    url(r'^flats/(?P<flat_id>[\w-]+)/tasks/$', task_views.TasksView.get_all_flat_tasks, name='flat-tasks'),

    url(r'^components/$', component_views.ComponentView.as_view(), name='components'),
    url(r'^components/add/$', component_views.ComponentAddView.as_view(), name='component-add'),
    url(r'^components/update/(?P<pk>[\w-]+)/$', component_views.ComponentUpdateView.as_view(), name='component-update'),
    url(r'^components/delete/$', component_views.ComponentView.delete, name='component-delete'),

    url(r'^building-plans/$', buildingplan_views.BuildingPlansView.get_all_plans_by_active_building, name='building-plans'),
    url(r'^building/(?P<building_id>[\w-]+)/plan/add/$', buildingplan_views.BuildingPlansAddView.as_view(), name='building-plan-add'),
    # url(r'^building-plan/update/(?P<pk>[\w-]+)/$', buildingplan_views.BuildingPlansUpdateView.as_view(), name='building-plan-update'),
    url(r'^building-plan/delete/$', buildingplan_views.BuildingPlansView.delete, name='building-plan-delete'),

    url(r'^flat-plans/$', flatplan_views.FlatPlansView.get_all_plans_by_active_flat, name='flat-plans'),
    url(r'^flat/(?P<flat_id>[\w-]+)/plan/add/$', flatplan_views.FlatPlansAddView.as_view(), name='flat-plan-add'),
    # url(r'^flat-plan/update/(?P<pk>[\w-]+)/$', flatplan_views.FlatPlansUpdateView.as_view(), name='flat-plan-update'),
    url(r'^flat-plan/delete/$', flatplan_views.FlatPlansView.delete, name='flat-plan-delete'),

    url(r'^project-plans/$', projectplan_views.ProjectPlansView.get_all_plans_by_active_project, name='project-plans'),
    url(r'^project/(?P<project_id>[\w-]+)/plan/add/$', projectplan_views.ProjectPlansAddView.as_view(), name='project-plan-add'),
    # url(r'^project-plan/update/(?P<pk>[\w-]+)/$', projectplan_views.ProjectPlansUpdateView.as_view(), name='project-plan-update'),
    url(r'^project-plan/delete/$', projectplan_views.ProjectPlansView.delete, name='project-plan-delete'),

    url(r'^sw.js', (TemplateView.as_view(template_name="sw.js", content_type='application/javascript', )), name='sw.js'),

    url(r'^qr-to-png/(?P<qr_id>[\w-]+)/$', common_views.QRResponse.as_view(), name='qr-to-png'),

    url(r'^current-buildings/$', common_views.CurrentProjects.get_all_current_buildings, name='current-buildings'),
    url(r'^current-project-buildings/$', common_views.CurrentProjects.get_all_buildings_by_active_project, name='current-project-buildings'),
    url(r'^current-project-flats/$', common_views.CurrentProjects.get_all_flats_by_active_building, name='current-project-flats'),
    url(r'^current-flats/$', common_views.CurrentProjects.get_all_current_flats, name='current-flats'),

    url(r'^get-pending-components/$', task_views.TasksView.get_pending_components, name='get-pending-components'),
    url(r'^get-done-components/$', task_views.TasksView.get_done_components, name='get-done-components'),
    url(r'^get-all-components/$', task_views.TasksView.get_all_components, name='get-all-components'),
    url(r'^get-component-tasks/$', task_views.TasksView.get_component_tasks, name='get-component-tasks'),
    url(r'^get-handworker-list/$', task_views.TasksView.get_handwerker_list, name='get-handworker-list'),
    url(r'^assign-handworker/$', task_views.TasksView.assign_handwerker, name='assign-handworker'),
    # url(r'^get-active-tasks/$', task_views.TasksView.get_active_tasks, name='get-active-tasks'),

    url(r'^tasks/(?P<task_id>[\w-]+)/$', task_views.TaskDetailsView.as_view(), name='task-details'),
    url(r'^save-task-description/$', task_views.TaskDetailsView.save_task_description, name='save-task-description'),
    url(r'^change-task-status/$', task_views.TaskDetailsView.change_task_status, name='change-task-status'),
    url(r'^change-task-deadline/$', task_views.TaskDetailsView.change_task_deadline, name='change-task-deadline'),
    url(r'^add-new-comment/(?P<task_id>[\w-]+)/$', task_views.TaskDetailsView.add_new_comment, name='add-new-comment'),
    url(r'^get-more-comments/$', task_views.TaskDetailsView.get_more_comments, name='get-more-comments'),
    url(r'^add-task-followers/$', task_views.TaskDetailsView.add_task_followers, name='add-task-followers'),
    url(r'^get-new-notifications/$', notification_views.NotificationsView.get_new_notifications, name='get-new-notifications'),
    url(r'^get-all-notifications/$', notification_views.NotificationsView.as_view(), name='get-all-notifications'),
    url(r'^get-more-notifications/$', notification_views.NotificationsView.get_more_notifications, name='get-more-notifications'),
    url(r'^read-all-notifications/$', notification_views.NotificationsView.read_all_notification, name='read-all-notifications'),
    url(r'^privacy_policy/$', misc_views.privacy_policy.as_view(), name='privacy_policy'),

    url(r'^update-database/$', update_database.UpdateDatabaseView.as_view(), name='update-database'),
    url(r'^update-database-request/$', update_database.UpdateDatabaseView.update_database, name='update-database-request'),


]

supplementer/urls.py
import notifications.urls
from django.conf.urls import include, url
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('', include('adminapp.urls')),
    path('api/', include('serviceapp.urls')),
    url('^inbox/notifications/', include(notifications.urls, namespace='notifications')),
]

from django.conf.urls.static import static
from django.conf import settings

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

adminapp/forms/building_form.py
from django import forms
from adminapp.models import Buildings
import re


class BuildingForm(forms.ModelForm):
    hause_number = forms.CharField(required=True, max_length=45)
    display_number = forms.CharField(required=True, max_length=45)
    grundung = forms.CharField(required=False, max_length=45)
    aussenwande_eg_og_dg = forms.CharField(required=False, max_length=45)
    fenster_beschattung = forms.CharField(required=False, max_length=45)
    dach = forms.CharField(required=False, max_length=45)
    description = forms.CharField(required=False, max_length=1000)

    class Meta:
        model = Buildings
        fields = ('hause_number', 'display_number', 'description', 'grundung', 'aussenwande_eg_og_dg', 'fenster_beschattung', 'dach')

    def clean(self):
        cleaned_data = super(BuildingForm, self).clean()

    def save(self, request, commit=True):
        cleaned_data = super(BuildingForm, self).clean()
        obj = super(BuildingForm, self).save(commit=False)
        obj.project_id = request.project_id
        obj.created_by = request.user
        obj.updated_by = request.user
        obj.save()
        return obj

    def update(self, request, commit=True):
        cleaned_data = super(BuildingForm, self).clean()
        obj = super(BuildingForm, self).save(commit=False)
        obj.updated_by = request.user
        obj.save()
        return obj

    def process(self):
        cd = self.cleaned_data

adminapp/forms/buildingplans_form.py
from django import forms
from adminapp.models import BuildingPlans


class BuildingPlansForm(forms.ModelForm):
    title = forms.CharField(label="title", max_length=100)
    plan_file = forms.FileField(label="plan_file", required=False)
    file_type = forms.CharField(max_length=45, required=False)

    class Meta:
        model = BuildingPlans
        fields = ('title', 'plan_file', 'file_type')

    def clean(self):
        cleaned_data = super(BuildingPlansForm, self).clean()
        title = cleaned_data.get('title')
        if BuildingPlans.objects.filter(title=title).exclude(pk=self.instance.id).exists():
            self.add_error('title', 'Plan is already exists.')

    def save(self, request, commit=True):
        cleaned_data = super(BuildingPlansForm, self).clean()
        obj = super(BuildingPlansForm, self).save(commit=False)
        obj.created_by = request.user
        obj.file_type = cleaned_data.get('plan_file').name.split('.')[-1]
        obj.building_id = request.building_id
        obj.save()
        return obj

    # def update(self, request, commit=True):
    #     cleaned_data = super(BuildingPlansForm, self).clean()
    #     obj = super(BuildingPlansForm, self).save(commit=False)
    #     obj.created_by = request.user
    #     obj.file_type = cleaned_data.get('plan_file').name.split('.')[-1]
    #     obj.building_id = 3
    #     obj.save()
    #     return obj

    def process(self):
        cd = self.cleaned_data

adminapp/forms/flat_form.py
from django import forms
from adminapp.models import Flats


class FlatForm(forms.ModelForm):
    number = forms.CharField(required=True, max_length=45)
    description = forms.CharField(required=False, max_length=1000)
    client_name = forms.CharField(required=False, max_length=100)
    client_address = forms.CharField(required=False, max_length=1000)
    client_email = forms.CharField(required=False, max_length=50)
    client_tel = forms.CharField(required=False, max_length=50)

    class Meta:
        model = Flats
        fields = ('number', 'description', 'client_name', 'client_address', 'client_email', 'client_tel')

    def clean(self):
        cleaned_data = super(FlatForm, self).clean()

    def save(self, request, commit=True):
        cleaned_data = super(FlatForm, self).clean()
        obj = super(FlatForm, self).save(commit=False)
        obj.building_id = request.building_id
        obj.created_by = request.user
        obj.updated_by = request.user
        obj.save()
        return obj

    def update(self, request, commit=True):
        cleaned_data = super(FlatForm, self).clean()
        obj = super(FlatForm, self).save(commit=False)
        obj.updated_by = request.user
        obj.save()
        return obj

    def process(self):
        cd = self.cleaned_data

adminapp/views.py
from django.shortcuts import render

# Create your views here.

adminapp/views/buildingplan_views.py
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render
from django.template.loader import render_to_string
from django.views import generic
from adminapp.forms.buildingplans_form import BuildingPlansForm
from adminapp.models import BuildingPlans
import json
from adminapp.views.helper import LogHelper


class BuildingPlansView(generic.DetailView):

    # url: building-plans/
    # This function will get all plans by a building
    def get_all_plans_by_active_building(request):
        response = {}
        try:
            building_id = request.session['active_building']['id']
            if 'building_id' in request.POST:
                building_id = request.POST.get('building_id')
            plans = BuildingPlans.objects.filter(building_id=building_id)
            plan_list_tab = render_to_string('buildings/plan.html', {"plans": plans, "building_id": building_id})
            response['plan_list_tab'] = plan_list_tab
            response['success'] = True
        except Exception as e:
            LogHelper.efail(e)
            response['success'] = False
            response['message'] = "Something went wrong. Please try again"
        return HttpResponse(json.dumps(response), content_type='application/json')

    # url: building-plan/delete/
    # This function will delete a building plan
    def delete(request):
        response = {}
        try:
            building_plan_id = request.POST.get('id')
            BuildingPlans.objects.get(id=building_plan_id).delete()
            response['success'] = True
            response['message'] = "Buildings Plan delete successfully"
        except Exception as e:
            LogHelper.elog(e)
            response['success'] = False
            response['message'] = "Something went wrong. Please try again"
        return HttpResponse(json.dumps(response), content_type='application/json')


class BuildingPlansAddView(generic.DetailView):
    form_class = BuildingPlansForm
    template_name = 'buildings/add_plans.html'

    # url: building/<building_id>/plan/add/
    # This function will show add building plan form
    def get(self, request, *args, **kwargs):
        building_id = kwargs['building_id']
        form = self.form_class
        return render(request, self.template_name, {'form': form, 'building_id': building_id})

    # url: building/<building_id>/plan/add/
    # This function will submit add building plan form
    def post(self, request, *args, **kwargs):
        response = {}
        form = self.form_class(request.POST, request.FILES)
        response['form'] = form
        building_id = kwargs['building_id']
        request.building_id = building_id
        response['building_id'] = building_id
        try:
            if form.is_valid():
                form.save(request=request)
                return HttpResponseRedirect('/buildings/'+str(building_id)+'/tasks/#plans')
            else:
                return render(request, self.template_name, response)
        except Exception as e:
            LogHelper.efail(e)
            return render(request, self.template_name, response)

adminapp/templates/flats/add_flat.html
{% extends "layout/main.html" %}
{% block content %}
    {% load staticfiles %}
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-left">
                        <li class="breadcrumb-item"><a href="{% url 'index' %}">Home</a></li>
                        <li class="breadcrumb-item active">Add Wohnung</li>
                    </ol>
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-header">

                            <div class="row">
                                <div class="col-sm">
                                    <h3 class="card-title">Add Wohnung</h3>
                                </div>
                            </div>
                        </div>
                        <!-- /.card-header -->
                        <div class="card-body">
                            <form id="form-add-flat" action="{% url 'flats-add' building_id=building_id %}"
                                  method="post">
                                {% csrf_token %}
                                {{ form.non_field_errors }}
                                <div class="row">
                                    <div class="col-sm-6 col-xs-12">
                                        <div class="form-group has-feedback">
                                            <label for="{{ form.number.id_for_label }}">Wohnung Number<span class="required-cls">*</span></label>
                                            <input type="text" id="id_number" name="number"
                                                   class="form-control" placeholder="Enter Wohnung number">
                                            {{ form.number.errors }}
                                        </div>
                                    </div>
                                    <div class="col-sm-6 col-xs-12">
                                        <div class="form-group has-feedback">
                                            <label for="{{ form.client_name.id_for_label }}">Client Name</label>
                                            <input type="text" id="id_client_name" name="client_name"
                                                   class="form-control" placeholder="Enter Client Name">
                                            {{ form.client_name.errors }}
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-sm-6 col-xs-12">
                                        <div class="form-group has-feedback">
                                            <label for="{{ form.client_email.id_for_label }}">Client Email</label>
                                            <input type="email" id="id_client_email" name="client_email"
                                                   class="form-control" placeholder="Enter Client Email">
                                            {{ form.client_email.errors }}
                                        </div>
                                    </div>
                                    <div class="col-sm-6 col-xs-12">
                                        <div class="form-group has-feedback">
                                            <label for="{{ form.client_tel.id_for_label }}">Client Telephone</label>
                                            <input type="text" id="id_client_tel" name="client_tel"
                                                   class="form-control" placeholder="Enter Client Telephone">
                                            {{ form.client_tel.errors }}
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-sm-12 col-xs-12">
                                        <div class="form-group has-feedback">
                                            <label for="{{ form.client_address.id_for_label }}">Client Address</label>
                                            <textarea class="form-control" rows="3" id="id_client_address" name="client_address"
                                                      placeholder="Enter Address"></textarea>
                                            {{ form.client_address.errors }}
                                        </div>
                                    </div>
                                    <div class="col-sm-12 col-xs-12">
                                        <div class="form-group has-feedback">
                                            <label for="{{ form.description.id_for_label }}">Wohnung Description</label>
                                            <textarea class="form-control" rows="3" id="id_description" name="description"
                                                      placeholder="Enter Description"></textarea>
                                            {{ form.description.errors }}
                                        </div>
                                    </div>
                                    <div class="col-sm-6 col-xs-12">
                                        <button type="submit" class="btn btn-primary">Add Wohnung</button>
                                    </div>
                                </div>

                            </form>

                            <!-- /.card-body -->
                        </div>
                        <!-- /.col-lg-6 -->
                    </div>
                    <!-- /.row -->
                </div>
                <!-- /.container-fluid -->
            </div>
            <!-- /.content -->
        </div>
    </div>
    <script>
        $(function () {
            $("#form-add-flat").validate({
                ignore: '.ignore',
                focusInvalid: true,
                rules: {
                    'number': {
                        required: true
                    },
                    'client_name': {
                        required: false
                    },
                    'client_email': {
                        required: false
                    },
                    'client_tel': {
                        required: false,
                        phonevalidate: true
                    },
                    'client_address': {
                        required: false
                    },
                    'description': {
                        required: false,
                    }
                }
            });
            $('#form-add-flat').on('submit', function () {
                if ($(this).valid()) {
                    return true;
                }
                return false;
            });
        });
    </script>

{% endblock %}

adminapp/templates/flats/add_plans.html
{% extends "layout/main.html" %}
{% block content %}
    {% load staticfiles %}
        <div class="content-header">
                <div class="container-fluid">
                    <div class="row mb-2">
                        <!-- /.col -->
                        <div class="col-sm-6">
                            <ol class="breadcrumb float-sm-left">
                                <li class="breadcrumb-item"><a href="#">Home</a></li>
                                <li class="breadcrumb-item active">Add Plan</li>
                            </ol>
                        </div>
                        <!-- /.col -->
                    </div>
                    <!-- /.row -->
                </div>
                <!-- /.container-fluid -->
            </div>
            <!-- /.content-header -->

            <!-- Main content -->
            <div class="content">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="card">
                                <div class="card-header">

                                    <div class="row">
                                        <div class="col-sm">
                                            <h3 class="card-title">Add Plan</h3>
                                        </div>
                                    </div>
                                </div>
                                <!-- /.card-header -->
                                <div class="card-body">
                                    <form action="{% url 'flat-plan-add' flat_id=flat_id %}" method="post" enctype="multipart/form-data" id="form-add-flat-plans">
                                        {% csrf_token %}
                                        {{ form.non_field_errors }}
                                        <div class="row">
                                            <div class="col-sm-3  col-xs-12 align-items-center justify-content-center chg_image_profile">
                                                <div class="row">
                                                    <div class="col-sm-8 offset-sm-2 col-xs-12">
                                                        <div class="form-group">
                                                            <div class=" imgUp">
                                                                <div class="imagePreview"></div>
                                                                <label class="btn btn-primary btn_up_image w-100">
                                                                    Select plan<input type="file" class="uploadFile img" value="Select plan" name="plan_file" style="width: 0px;height: 0px;overflow: hidden;" required="">
                                                                </label>
                                                                {{ form.plan_file.errors }}
                                                            </div><!-- col-2 -->
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="col-sm-8 col-xs-12">
                                                <div class="form-group">
                                                    <label for="{{ form.title.id_for_label }}">Plan name<span class="required-cls">*</span></label>
                                                    <input type="text" class="form-control" id="id_title" name="title" placeholder="Enter Plan name" data-parsley-trigger="change" required="">
                                                    {{ form.title.errors }}
                                                </div>
                                                <button type="submit" class="btn btn-primary">Add Plan</button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                                    <!-- /.card-body -->
                            </div>
                                <!-- /.col-lg-6 -->
                        </div>
                            <!-- /.row -->
                    </div>
                        <!-- /.container-fluid -->
                </div>
                    <!-- /.content -->
            </div>
    <script type="text/javascript">
        $('.uploadFile').change(function() {
          var file = $('.uploadFile')[0].files[0].name.split('.');
          file = file[file.length-1];

          if(file != 'pdf'){
              $('.imagePreview').attr('background-image','url(../../static/assets/images/file.png)');
          }
          $(this).prev('label').text(file);
        });
        $(function () {
            $("#form-add-flat-plans").validate({
                ignore: '.ignore',
                focusInvalid: true,
                rules: {
                    'title': {
                        required: true
                    },
                    'plan_file': {
                        required: true
                    }
                }
            });
            $('#form-add-flat-plans').on('submit', function () {
                if ($(this).valid()) {
                    return true;
                }
                return false;
            });
        });
    </script>

                <!-- /.content-wrapper -->
    {% include "layout/datatable_footer.html" %}
{% endblock %}