adminapp/urls.py
from django.conf.urls import url
from django.urls import path
from django.views.generic import TemplateView

from adminapp.views import common_views, login_views, staff_views, company_views, project_views, building_views, \
    flat_views, buildingplan_views, flatplan_views, component_views, reset_password, datatables, profile_views, \
    projectplan_views, task_views, notification_views, update_database, misc_views
from django.conf import settings
from django.views.static import serve
urlpatterns = [
    url(r'^$', common_views.IndexView.as_view(), name='index'),
    url(r'^login/$', login_views.LoginView.as_view(), name='login'),
    url(r'^logout/$', login_views.LogoutView.as_view(), name='logout'),
    url(r'^forget-password/$', reset_password.ResetPasswordRequestView.as_view(), name='forget-password'),
    url(r'^reset-password/$', reset_password.ResetPasswordView.as_view(), name='reset-password'),

    url(r'^profile/update/$', profile_views.ProfileUpdateView.as_view(), name='profile-update'),
    url(r'^change-password/$', profile_views.ChangePassword.as_view(), name='change-password'),

    url(r'^staffs/$', staff_views.StaffsView.as_view(), name='staffs'),
    url(r'^staffs/add/$', staff_views.StaffFormView.as_view(), name='staffs-add'),
    url(r'^staffs/update/(?P<pk>[\w-]+)/$', staff_views.StaffUpdateView.as_view(), name='staffs-update'),
    url(r'^staffs/delete/$', staff_views.StaffsView.delete, name='staffs-delete'),
    url(r'^staff-list/$', datatables.StaffListView.as_view(), name='staffList'),
    url(r'^staffs/change-password/(?P<pk>[\w-]+)$', staff_views.StaffPasswordChangeView.as_view(),name='staffs-password-update'),

    url(r'^companies/$', company_views.CompaniesView.as_view(), name='companies'),
    url(r'^companies/add/$', company_views.CompanyFormView.as_view(), name='companies-add'),
    url(r'^companies/update/(?P<pk>[\w-]+)/$', company_views.CompanyUpdateView.as_view(), name='companies-update'),
    url(r'^companies/delete/$', company_views.CompaniesView.delete, name='companies-delete'),
    url(r'^company-list/$', datatables.CompanyListView.as_view(), name='companyList'),
    url(r'^companies/change-password/(?P<pk>[\w-]+)$', company_views.CompanyPasswordChangeView.as_view(),name='companies-password-update'),

    url(r'^change-user-status/$', staff_views.StaffsView.change_user_status, name='change-user-status'),

    url(r'^projects/$', project_views.ProjectsView.as_view(), name='projects'),
    url(r'^projects/add/$', project_views.ProjectFormView.as_view(), name='projects-add'),
    url(r'^projects/update/(?P<pk>[\w-]+)/$', project_views.ProjectUpdateView.as_view(), name='projects-update'),
    url(r'^projects/delete/$', project_views.ProjectsView.delete, name='projects-delete'),
    url(r'^project-list/$', datatables.ProjectListView.as_view(), name='projectList'),

    url(r'^change-project-status/$', project_views.ProjectsView.change_project_status, name='change-project-status'),

    url(r'^projects/(?P<project_id>[\w-]+)/buildings/$', building_views.BuildingsView.as_view(), name='buildings'),
    url(r'^building-list/$', datatables.BuildingListView.as_view(), name='buildingList'),
    url(r'^projects/(?P<project_id>[\w-]+)/buildings/add/$', building_views.BuildingFormView.as_view(), name='buildings-add'),
    url(r'^buildings/update/(?P<pk>[\w-]+)/$', building_views.BuildingUpdateView.as_view(), name='buildings-update'),
    url(r'^buildings/delete/$', building_views.BuildingsView.delete, name='buildings-delete'),
    url(r'^buildings/qr/(?P<pk>[\w-]+)/$', building_views.BuildingsView.preview_qr, name='buildings-qr'),
    url(r'^buildings/(?P<building_id>[\w-]+)/tasks/$', task_views.TasksView.get_all_building_tasks, name='building-tasks'),

    url(r'^buildings/(?P<building_id>[\w-]+)/flats/$', flat_views.FlatsView.as_view(), name='flats'),
    url(r'^flats-list/$', datatables.FlatListView.as_view(), name='flatList'),
    url(r'^buildings/(?P<building_id>[\w-]+)/flats/add/$', flat_views.FlatFormView.as_view(), name='flats-add'),
    url(r'^flats/update/(?P<pk>[\w-]+)/$', flat_views.FlatUpdateView.as_view(), name='flats-update'),
    url(r'^flats/delete/$', flat_views.FlatsView.delete, name='flats-delete'),
    url(r'^flats/qr/(?P<pk>[\w-]+)/$', flat_views.FlatsView.preview_qr, name='flats-qr'),
    url(r'^flats/(?P<flat_id>[\w-]+)/tasks/$', task_views.TasksView.get_all_flat_tasks, name='flat-tasks'),

    url(r'^components/$', component_views.ComponentView.as_view(), name='components'),
    url(r'^components/add/$', component_views.ComponentAddView.as_view(), name='component-add'),
    url(r'^components/update/(?P<pk>[\w-]+)/$', component_views.ComponentUpdateView.as_view(), name='component-update'),
    url(r'^components/delete/$', component_views.ComponentView.delete, name='component-delete'),

    url(r'^building-plans/$', buildingplan_views.BuildingPlansView.get_all_plans_by_active_building, name='building-plans'),
    url(r'^building/(?P<building_id>[\w-]+)/plan/add/$', buildingplan_views.BuildingPlansAddView.as_view(), name='building-plan-add'),
    # url(r'^building-plan/update/(?P<pk>[\w-]+)/$', buildingplan_views.BuildingPlansUpdateView.as_view(), name='building-plan-update'),
    url(r'^building-plan/delete/$', buildingplan_views.BuildingPlansView.delete, name='building-plan-delete'),

    url(r'^flat-plans/$', flatplan_views.FlatPlansView.get_all_plans_by_active_flat, name='flat-plans'),
    url(r'^flat/(?P<flat_id>[\w-]+)/plan/add/$', flatplan_views.FlatPlansAddView.as_view(), name='flat-plan-add'),
    # url(r'^flat-plan/update/(?P<pk>[\w-]+)/$', flatplan_views.FlatPlansUpdateView.as_view(), name='flat-plan-update'),
    url(r'^flat-plan/delete/$', flatplan_views.FlatPlansView.delete, name='flat-plan-delete'),

    url(r'^project-plans/$', projectplan_views.ProjectPlansView.get_all_plans_by_active_project, name='project-plans'),
    url(r'^project/(?P<project_id>[\w-]+)/plan/add/$', projectplan_views.ProjectPlansAddView.as_view(), name='project-plan-add'),
    # url(r'^project-plan/update/(?P<pk>[\w-]+)/$', projectplan_views.ProjectPlansUpdateView.as_view(), name='project-plan-update'),
    url(r'^project-plan/delete/$', projectplan_views.ProjectPlansView.delete, name='project-plan-delete'),

    url(r'^sw.js', (TemplateView.as_view(template_name="sw.js", content_type='application/javascript', )), name='sw.js'),

    url(r'^qr-to-png/(?P<qr_id>[\w-]+)/$', common_views.QRResponse.as_view(), name='qr-to-png'),

    url(r'^current-buildings/$', common_views.CurrentProjects.get_all_current_buildings, name='current-buildings'),
    url(r'^current-project-buildings/$', common_views.CurrentProjects.get_all_buildings_by_active_project, name='current-project-buildings'),
    url(r'^current-project-flats/$', common_views.CurrentProjects.get_all_flats_by_active_building, name='current-project-flats'),
    url(r'^current-flats/$', common_views.CurrentProjects.get_all_current_flats, name='current-flats'),

    url(r'^get-pending-components/$', task_views.TasksView.get_pending_components, name='get-pending-components'),
    url(r'^get-done-components/$', task_views.TasksView.get_done_components, name='get-done-components'),
    url(r'^get-all-components/$', task_views.TasksView.get_all_components, name='get-all-components'),
    url(r'^get-component-tasks/$', task_views.TasksView.get_component_tasks, name='get-component-tasks'),
    url(r'^get-handworker-list/$', task_views.TasksView.get_handwerker_list, name='get-handworker-list'),
    url(r'^assign-handworker/$', task_views.TasksView.assign_handwerker, name='assign-handworker'),
    # url(r'^get-active-tasks/$', task_views.TasksView.get_active_tasks, name='get-active-tasks'),

    url(r'^tasks/(?P<task_id>[\w-]+)/$', task_views.TaskDetailsView.as_view(), name='task-details'),
    url(r'^save-task-description/$', task_views.TaskDetailsView.save_task_description, name='save-task-description'),
    url(r'^change-task-status/$', task_views.TaskDetailsView.change_task_status, name='change-task-status'),
    url(r'^change-task-deadline/$', task_views.TaskDetailsView.change_task_deadline, name='change-task-deadline'),
    url(r'^add-new-comment/(?P<task_id>[\w-]+)/$', task_views.TaskDetailsView.add_new_comment, name='add-new-comment'),
    url(r'^get-more-comments/$', task_views.TaskDetailsView.get_more_comments, name='get-more-comments'),
    url(r'^add-task-followers/$', task_views.TaskDetailsView.add_task_followers, name='add-task-followers'),
    url(r'^get-new-notifications/$', notification_views.NotificationsView.get_new_notifications, name='get-new-notifications'),
    url(r'^get-all-notifications/$', notification_views.NotificationsView.as_view(), name='get-all-notifications'),
    url(r'^get-more-notifications/$', notification_views.NotificationsView.get_more_notifications, name='get-more-notifications'),
    url(r'^read-all-notifications/$', notification_views.NotificationsView.read_all_notification, name='read-all-notifications'),
    url(r'^privacy_policy/$', misc_views.privacy_policy.as_view(), name='privacy_policy'),

    url(r'^update-database/$', update_database.UpdateDatabaseView.as_view(), name='update-database'),
    url(r'^update-database-request/$', update_database.UpdateDatabaseView.update_database, name='update-database-request'),


]

supplementer/urls.py
import notifications.urls
from django.conf.urls import include, url
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('', include('adminapp.urls')),
    path('api/', include('serviceapp.urls')),
    url('^inbox/notifications/', include(notifications.urls, namespace='notifications')),
]

from django.conf.urls.static import static
from django.conf import settings

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

adminapp/forms/project_form.py
from django import forms
from adminapp.models import Projects
import re


class ProjectForm(forms.ModelForm):
    name = forms.CharField(required=True, max_length=200)
    address = forms.CharField(required=False, max_length=1000)
    description = forms.CharField(required=False, max_length=1000)
    type = forms.CharField(required=False, max_length=100)
    city = forms.CharField(required=False, max_length=100)
    energetic_standard = forms.CharField(required=False, max_length=100)
    start_date = forms.DateTimeField(required=False)
    end_date = forms.DateTimeField(required=False)

    class Meta:
        model = Projects
        fields = ('name', 'address', 'description', 'type', 'city', 'energetic_standard', 'start_date', 'end_date')

    def clean(self):
        cleaned_data = super(ProjectForm, self).clean()
        name = cleaned_data.get('name')
        if Projects.objects.filter(name=name).exclude(pk=self.instance.id).exists():
            self.add_error('name', 'Project name is already exists.')

    def save(self, request, commit=True):
        cleaned_data = super(ProjectForm, self).clean()
        obj = super(ProjectForm, self).save(commit=False)
        obj.created_by = request.user
        obj.updated_by = request.user
        obj.save()
        return obj

    def update(self, request, commit=True):
        cleaned_data = super(ProjectForm, self).clean()
        obj = super(ProjectForm, self).save(commit=False)
        obj.updated_by = request.user
        obj.save()
        return obj

    def process(self):
        cd = self.cleaned_data

adminapp/forms/user_form.py
from django import forms
from adminapp.models import Users, ProjectStuff
import re


class ProfileForm(forms.ModelForm):
    username = forms.CharField(required=True, max_length=45)
    first_name = forms.CharField(required=False, max_length=45)
    last_name = forms.CharField(required=False, max_length=45)
    email = forms.CharField(required=True, max_length=45)
    avatar = forms.FileField(required=False)
    address = forms.CharField(required=False, max_length=1000)
    is_active = forms.CharField(required=False, max_length=1)

    class Meta:
        model = Users
        fields = ('username', 'first_name', 'last_name', 'email', 'is_active', 'address', 'avatar')

        def clean(self):
            cleaned_data = super(ProfileForm, self).clean()
            if Users.objects.filter(email=cleaned_data.get("email")).exclude(pk=self.instance.id).exists():
                self.add_error('email', 'A user with that email already exists')


class UserForm(ProfileForm):
    password = forms.CharField(widget=forms.PasswordInput())
    confirm_password = forms.CharField(required=True)
    project_list = forms.CharField(required=False, max_length=1000)

    class Meta:
        model = Users
        fields = ('username', 'first_name', 'last_name', 'email', 'password', 'is_active', 'address', 'avatar', 'project_list')

    def clean(self):
        cleaned_data = super(ProfileForm, self).clean()
        password = cleaned_data.get("password")
        confirm_password = cleaned_data.get("confirm_password")

        if password != confirm_password:
            self.add_error('confirm_password', 'Passwords do not match.')

        if Users.objects.filter(email=cleaned_data.get("email")).exists():
            self.add_error('email', 'A user with that email already exists.')

    def save(self, request, commit=False):
        # cleaned_data = super(ProfileForm, self).clean()
        obj = super(UserForm, self).save(commit=False)
        obj.is_active = "1"
        obj.is_staff = "1"
        obj.set_password(self.cleaned_data['password'])
        obj.save()
        return obj


class UserUpdateForm(ProfileForm):

    class Meta:
        model = Users
        fields = ('username', 'first_name', 'last_name', 'email', 'address', 'avatar')

    def clean(self):
        cleaned_data = super(ProfileForm, self).clean()
        if Users.objects.filter(email=cleaned_data.get("email")).exclude(pk=self.instance.id).exists():
            self.add_error('email', 'A user with that email already exists.')
        if cleaned_data.get("avatar") != self.instance.avatar:
            self.instance.avatar.delete(save=False)

    def update(self, request, commit=True):
        obj = super(ProfileForm, self).save(commit=False)
        obj.save()
        return obj


class WorkerForm(ProfileForm):
    password = forms.CharField(widget=forms.PasswordInput())
    confirm_password = forms.CharField(required=True)
    telephone_office = forms.CharField(required=False, max_length=45)
    telephone_mobile = forms.CharField(required=False, max_length=45)
    company_name = forms.CharField(required=True, max_length=100)
    working_type = forms.CharField(required=True, max_length=1000)

    class Meta:
        model = Users
        fields = ('username', 'first_name', 'last_name', 'email', 'password', 'is_active', 'address', 'avatar', 'working_type')

    def clean(self):
        cleaned_data = super(ProfileForm, self).clean()
        password = cleaned_data.get("password")
        confirm_password = cleaned_data.get("confirm_password")

        if password != confirm_password:
            self.add_error('confirm_password', 'Passwords do not match.')

        if Users.objects.filter(email=cleaned_data.get("email")).exists():
            self.add_error('email', 'A user with that email already exists.')

    def save(self, request, commit=False):
        # cleaned_data = super(ProfileForm, self).clean()
        obj = super(WorkerForm, self).save(commit=False)
        obj.is_active = "1"
        obj.is_staff = "0"
        obj.set_password(self.cleaned_data['password'])
        obj.save()
        return obj


class WorkerUpdateForm(ProfileForm):
    telephone_office = forms.CharField(required=False, max_length=45)
    telephone_mobile = forms.CharField(required=False, max_length=45)
    company_name = forms.CharField(required=True, max_length=100)
    working_type = forms.CharField(required=True, max_length=1000)

    class Meta:
        model = Users
        fields = ('username', 'first_name', 'last_name', 'email', 'address', 'avatar')

    def clean(self):
        cleaned_data = super(ProfileForm, self).clean()
        if Users.objects.filter(email=cleaned_data.get("email")).exclude(pk=self.instance.id).exists():
            self.add_error('email', 'A user with that email already exists.')
        if cleaned_data.get("avatar") != self.instance.avatar:
            self.instance.avatar.delete(save=False)

    def update(self, request, commit=True):
        obj = super(ProfileForm, self).save(commit=False)
        obj.save()
        return obj


class UserPasswordChangeForm(forms.ModelForm):

    password = forms.CharField(widget=forms.PasswordInput(), max_length=200, min_length=6)
    confirm_password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = Users
        fields = ('password',)

    def clean(self):
        cleaned_data = super(UserPasswordChangeForm, self).clean()
        password = cleaned_data.get("password")
        confirm_password = cleaned_data.get("confirm_password")

        if password != confirm_password:
            self.add_error('confirm_password', 'Passwords do not match.')

    def save(self, request, commit=False):
        obj = super(UserPasswordChangeForm, self).save(commit=False)
        obj.set_password(self.cleaned_data['password'])
        obj.save()
        return obj

adminapp/views.py
from django.shortcuts import render

# Create your views here.

adminapp/templates/staffs/add_staff.html
{% extends "layout/main.html" %}
{% block content %}
    {% load staticfiles %}
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <!-- /.col -->
                <div class="col-sm-6">
                    <!-- <ol class="breadcrumb float-sm-left">
                        <li class="breadcrumb-item"><a href="{% url 'index' %}">Home</a></li>
                        <li class="breadcrumb-item active">Add Staff</li>
                    </ol> -->
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-header">

                            <div class="row">
                                <div class="col-sm">
                                    <h3 class="card-title">Benutzer Hinzufügen</h3>
                                </div>
                            </div>
                        </div>
                        <!-- /.card-header -->
                        <div class="card-body">
                            <form id="form-add-staff" action="{% url 'staffs-add' %}" method="post"
                                  enctype="multipart/form-data">
                                {% csrf_token %}
                                {{ form.non_field_errors }}
                                <div class="row">
                                    <div class="col-sm-3  col-xs-12 align-items-center justify-content-center chg_image_profile">
                                        <div class="row">
                                            <div class="col-sm-8 offset-sm-2 col-xs-12">
                                                <div class="form-group">
                                                    <div class="has-feedback imgUp">
                                                        <div class="imagePreview"></div>
                                                        <label class="btn btn-primary btn_up_image w-100">
                                                            Bild Auswählen<input type="file" class="uploadFile img"
                                                                         id="id_avatar" name="avatar"
                                                                         value="Upload Photo"
                                                                         style="width: 0px;height: 0px;overflow: hidden;">

                                                        </label>
                                                        {{ form.avatar.errors }}
                                                    </div><!-- col-2 -->
                                                </div>

                                            </div>
                                        </div>

                                    </div>
                                    <div class="col-sm-8 col-xs-12">
                                        <div class="form-group">
                                            <label for="{{ form.first_name.id_for_label }}">Vorname<span class="required-cls">*</span></label>
                                            <div class="has-feedback">
                                                <input type="text" id="id_first_name" name="first_name" value="{{ form.first_name.value|default_if_none:'' }}"
                                                       class="form-control" placeholder="Enter First name">
                                                {{ form.first_name.errors }}
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label for="{{ form.last_name.id_for_label }}">Nachname<span class="required-cls">*</span></label>
                                            <div class="has-feedback">
                                                <input type="text" class="form-control" id="id_last_name"
                                                       name="last_name" value="{{ form.last_name.value|default_if_none:'' }}"
                                                       placeholder="Enter Last Name">
                                                {{ form.last_name.errors }}
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label for="{{ form.username.id_for_label }}">Benutzername<span class="required-cls">*</span></label>
                                            <div class="has-feedback">
                                                <input type="text" class="form-control" id="id_username" name="username" value="{{ form.username.value|default_if_none:'' }}"
                                                       placeholder="Enter User name">
                                                {{ form.username.errors }}
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label for="{{ form.email.id_for_label }}">Email addresse<span class="required-cls">*</span></label>
                                            <div class="has-feedback">
                                                <input type="email" class="form-control" id="id_email" name="email" value="{{ form.email.value|default_if_none:'' }}"
                                                       placeholder="Enter email">
                                                {{ form.email.errors }}
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label for="{{ form.password.id_for_label }}">Passwort<span class="required-cls">*</span></label>
                                            <div class="has-feedback">
                                                <input type="password" class="form-control" id="id_password"
                                                       name="password"
                                                       placeholder="Enter Password">
                                                {{ form.password.errors }}
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label for="{{ form.confirm_password.id_for_label }}">Passwort Bestätigen
                                                <span class="required-cls">*</span></label>
                                            <div class="has-feedback">
                                                <input type="password" class="form-control" id="id_confirm_password"
                                                       name="confirm_password"
                                                       placeholder="Confirm Password">
                                                {{ form.confirm_password.errors }}
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <input type="hidden" id="project_list_selection" value='{{ project_list }}'>
                                            <label for="{{ form.project_list.id_for_label }}">Assigned Projects</label>
                                            <div class="has-feedback">
                                                <select class="form-control select2" multiple
                                                        id="id_project_list" name="project_list"
                                                        data-placeholder="Select projects"
                                                        style="width: 100%;">
                                                    {% for project in projects %}
                                                        <option value="{{ project.id }}">{{ project.name }}</option>
                                                    {% endfor %}
                                                </select>
                                                {{ form.project_list.errors }}
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label for="{{ form.address.id_for_label }}">Addresse</label>
                                            <div class="has-feedback">
                                                        <textarea id="id_address" name="address" class="form-control"
                                                                  placeholder="Enter staff address"
                                                                  style="width: 100%; height: 100px; font-size: 14px; line-height: 18px; border: 1px solid #dddddd; padding: 10px;">{{ form.address.value|default_if_none:'' }}</textarea>
                                                {{ form.address.errors }}
                                            </div>
                                        </div>
                                    </div>

                                    <div class="col-sm-6 offset-sm-3 col-xs-12">
                                        <button type="submit" class="btn btn-primary">Benutzer Hinzufügen</button>

                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.col-lg-6 -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /.container-fluid -->
    </div>
    <!-- /.content -->
    <script>
        $(function () {
            $('#id_project_list').select2();
            $("#form-add-staff").validate({
                ignore: '.ignore',
                focusInvalid: true,
                rules: {
                    'username': {
                        required: true
                    },
                    'first_name': {
                        required: true
                    },
                    'last_name': {
                        required: true
                    },
                    'email': {
                        required: true
                    },
                    'password': {
                        required: true,
                        minlength: 6
                    },
                    'confirm_password': {
                        required: true,
                        minlength: 6,
                        equalTo: 'input[name="password"]'
                    },
                    'address': {
                        required: false
                    },
                    'avatar': {
                        required: false
                    }
                }
            });
            $('#form-add-staff').on('submit', function () {
                if ($(this).valid()) {
                    return true;
                }
                return false;
            });
            var project_list = $("#project_list_selection").val().replace(/'/g, '"');
            if(project_list != ''){
                $('#id_project_list').select2('val', JSON.parse(project_list));
            }
        });
    </script>
{% endblock %}